# Generated by Django 4.2.7 on 2023-12-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date', '-updated'], 'verbose_name_plural': 'Products'},
        ),
    ]
